### ISSUE TITLE
Need variadic

### ISSUE THREAD

**Issue by zh-lab** [apex/log#12]
Will apex/log support api like `log.Debug(args ...interface{})`?

For now, I can only pass a string to log functions, sometimes it's not very convenience.

**Comment by zh-lab** [comment]
Also need a default handler for log singleton to prevent panic.

**Comment by tj** [comment]
There's `log.Debugf("uploading %s", filename)` or `log.WithField("file", filename).Debug("upload")`. 

Yep! There's an issue open for that #6
