### ISSUE TITLE
Interface is broken

### ISSUE THREAD

**Issue by santacruz123** [apex/log#18]
`⇒  go run cli.go
# command-line-arguments
./cli.go:12: cannot use cli.Default (type *cli.Handler) as type "github.com/apex/log".Handler in argument to "github.com/apex/log".SetHandler:
	*cli.Handler does not implement "github.com/apex/log".Handler (wrong type for HandleLog method)
		have HandleLog(*"github.com/apex/log/vendor/github.com/apex/log".Entry) error
		want HandleLog(*"github.com/apex/log".Entry) error`

**Comment by tj** [comment]
Can you elaborate? Is this _examples/cli/cli? it works fine for me:

```
$ go run _examples/cli/cli.go 
   • uploading                 file=something.png type=image/png user=tobi
   • upload complete           file=something.png type=image/png user=tobi
   • uploading                 file=something.png type=image/png user=tobi
   • upload complete           file=something.png type=image/png user=tobi
```

**Comment by tj** [comment]
oh I see, you have a vendor and non-vendor version, Go treats them as separate packages
