### ISSUE TITLE
Optionally disable ANSI characters in log output?

### ISSUE THREAD

**Issue by lox** [apex/log#22]
I'm outputting logs to syslog via upstart and the ANSI characters seem to end up garbled. Is there a way to disable ANSI output for the `cli` or `text` loggers?

**Comment by francoishill** [comment]
Hi @lox. I suspect the answer is to write a custom handler specific for that. You are probably using the text or cli handler now. Here is the list of built-in handlers: https://github.com/apex/log/tree/master/handlers.

If you look at the example on [medium](https://medium.com/@tjholowaychuk/apex-log-e8d9627f4a9a#.5j458rx5w) they use the `text` handler by calling `log.SetHandler(text.New(os.Stderr))`.

**Comment by tj** [comment]
Those two are pretty dev-centric, I'd use logfmt or json for production stuff, currently no way to disable

**Comment by lox** [comment]
Would you accept a patch to the text formatter that made it behave more like https://github.com/Sirupsen/logrus/blob/master/text_formatter.go and detect TTY and disable fancy colors accordingly?

**Comment by tj** [comment]
Hmm I don't see why personally, the little time ticker isn't very useful in production anyway, I just swap out the handler entirely to something more machine-friendly
