### ISSUE TITLE
Tags

### ISSUE THREAD

**Issue by cyphar** [apex/log#38]
Currently this project has no tagged releases, making vendoring harder than it should be.

**Comment by tj** [comment]
Nothing gets into master without being stable, so picking a SHA should be fine, I don't really version Go stuff

**Comment by cyphar** [comment]
The problem isn't stability, the problem is API compatibility.

**Comment by tj** [comment]
Sure, most Go people avoid breaking any API compat in a given repo, or do ./v2 etc. If there's any plan to break compat I'll tag 1.x

**Comment by cyphar** [comment]
"Most Go people" is a bit of a stretch, but thanks for at least having some plan for what to do when/if the API breaks.

**Comment by tj** [comment]
I'd still use SHAs personally, over semver style even if/when Go supports that. So many things that aren't API changes can still arguably be breaking changes.
