### ISSUE TITLE
time.Duration.Round not found?

### ISSUE THREAD

**Issue by matthewmueller** [apex/log#45]
Trying the new delta handler out, but getting build errors. Is it in Go 1.9?

**Comment by tj** [comment]
ohh oops yeah I've been running the betas, didn't realize it was a new API!

**Comment by matthewmueller** [comment]
ahh got it, i tried upgrading but ran into a world of pain haha. i'll wait until stable 👍

**Comment by tj** [comment]
There's a dmg somewhere, should override the current install with a few clicks
