### ISSUE TITLE
Why prefix with second value in every log ?

### ISSUE THREAD

**Issue by Wang-Kai** [apex/log#61]
I want to ask a question :  why dose put second time since program start at log pattern .

Dose it can help us while trace the log ? What is the meaning or target of it ?

<img width="713" alt="2018-06-05 11 53 03" src="https://user-images.githubusercontent.com/13144386/40954457-493c4c38-68b7-11e8-9f28-10d56ee45ac4.png">

**Comment by tj** [comment]
Yeah it's just a relative timestamp to help show when things have happened in development, but you can utilize one of the other handlers in production for a UTC timestamp, the "text" handler is more for local dev

**Comment by Wang-Kai** [comment]
Thank you very much .
