### ISSUE TITLE
Invoke Now() that result is zero time!

### ISSUE THREAD

**Issue by gratno** [apex/log#70]
<code>fmt.Println(log.Now())</code>
Result : 1970-01-01 08:00:00 +0800 CST

**Comment by tj** [comment]
ah it's not really public api, it's just an alias of `time.Now()` for swapping out in unit-tests (https://github.com/apex/log/blob/master/entry.go#L14)

**Comment by gratno** [comment]
I don't know why this alias got the error result before, just now I retry, got right result ..
