### ISSUE TITLE
Allow Trace.Stop(*error) to be called multiple times and only log once 

### ISSUE THREAD

**Issue by matthewmueller** [apex/log#77]
If you have:

```go
func (a *API) Check(w http.ResponseWriter, r *http.Request) {
  log := a.log.Trace("check")
  defer log.Stop(nil)
  if err := check(); err != nil {
    log.Stop(&err)
    return
  }
}
```

If there's an error, you'll have two log entries for stopping the trace. It'd be great do only log once for the first one.

**Comment by tj** [comment]
Need to think about tracing some more, it might be nice to do a 2.0 that is more like opentracing or something already established

**Comment by matthewmueller** [comment]
Agreed!

**Comment by wesleimp** [comment]
@tj can we close this issue?

**Comment by matthewmueller** [comment]
I don't think this is solved, but I also haven't run into it since Dec 2019 haha.
